export enum Auths {
    ADMIN = "ROLE_ADMIN",
    SUPORTE = "ROLE_SUPORTE",
    CADCONTRACT = "ROLE_CADCONTRACT",
    CADCONTRATYPE = "ROLE_CADCONTRATYPE",
    CADUSER = 'ROLE_CADUSER',
    CADADITIVO = "ROLE_CADADITIVO",
    SIGECON_PUBLICO = "ROLE_SIGECON_PUBLICO"
}
